########### Resources ###########
resources:
  - name: source
    type: git
    source:
      branch: main
      uri: https://github.com/ztwoettinger/security-chef
      # private_key: ((git-key))
    check_every: 8760h

  - name: version-build
    type: git
    icon: library
    check_every: 8760h
    source:
      driver: git
      uri: https://github.com/ztwoettinger/security-chef.git
      # private_key: ((git-key))
      branch: version
      depth: 1
      file: version-build

  - name: docker-registry
    type: registry-image
    icon: docker
    source:
      repository: tigelton/security-chef
      username: ((dockerhub-username))
      password: ((dockerhub-password))

######### End Resources #########


########### Jobs ###########
jobs:
- name: build-and-push
  plan:
  - get: source
  - get: version-build
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: source
      outputs:
      - name: image
      params:
        CONTEXT: source/Dockerfile
      run:
        path: build
  - put: docker-registry
    params:
      image: image/image.tar
      additional_tags: version-build/version