########### Resources ###########
resources:
  - name: source
    type: git
    source:
      branch: main
      uri: https://github.com/ztwoettinger/security-chef
      # private_key: ((git-key))
    check_every: 8760h

  - name: version-build
    type: semver
    icon: tag
    check_every: 8760h
    source:
      driver: git
      uri: https://github.com/ztwoettinger/security-chef.git
      # private_key: ((git-key))
      branch: version
      depth: 1
      file: version-build

  - name: security-chef
    type: registry-image
    icon: docker
    source:
      repository: tigelton/security-chef
      username: ((dockerhub-username))
      password: ((dockerhub-password))

######### End Resources #########


########### Jobs ###########
jobs:
- name: set-build-version
  public: true
  build_logs_to_retain: 3
  plan:
  - get: source
    trigger: true
    version: every
  - put: version-build
    params: {pre: build}

- name: quality-build
  plan:
  - get: source
    passed: [set-build-version]
    trigger: true
    params:
      integration_tool: checkout
  - get: version-build

  - task: run-tests
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: library/python
      inputs:
      - name: source
      outputs:
      - name: sonarqube-analysis-input
      run:
        path: /bin/sh
        args:
          - -xc
          - |
            cp -r source/. sonarqube-analysis-input
            cd sonarqube-analysis-input
            pip install -r requirements.txt
            chmod +x run-tests.sh
            ./run-tests.sh

  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: source
      outputs:
      - name: image
      params:
        CONTEXT: source
      run:
        path: build
  - put: security-chef
    params:
      image: image/image.tar
      additional_tags: version-build/version

########### End Jobs ###########