# Generated by Django 3.2.16 on 2023-03-27 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230327_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 18, 54, 18, 943085, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='run_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
