# Generated by Django 3.2.16 on 2023-03-27 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230327_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 20, 40, 22, 674779, tzinfo=utc)),
        ),
    ]
