# Generated by Django 3.2.16 on 2023-03-27 20:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_job_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 20, 44, 20, 892861, tzinfo=utc)),
        ),
    ]
